server:
  port: 9091

spring:
  application:
    name: login_service

  datasource:
    url: jdbc:mysql://localhost:3306/signin
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
